name: Build .NET Framework App

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore packages
        run: nuget restore .\WindowsFormsApp1.sln

      - name: Build solution
        run: msbuild .\WindowsFormsApp1.sln /p:Configuration=Release
